services:
  ca-db:
    container_name: ca-db
    image: mariadb:10.5
    volumes:
      - ca-db-vl:/var/lib/mysql
      - ./scripts/sql:/docker-entrypoint-initdb.d
    env_file:
      - ./environments/db/dev.env
    ports:
      - "3307:3306"
    expose:
      - 3306
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    networks:
      - ca-nw
  ca-app:
    build:
      context: .
      dockerfile: Dockerfile.app
    command: python manage.py runserver --noreload 0.0.0.0:8000
    container_name: ca-app
    volumes:
      - ./constructal_automate/:/app
      - "D:/constructal_automate_analysis_files:/mnt/data"
      - ./scripts/bash:/mnt/scripts
    ports:
      - "8000:8000"
    env_file:
      - ./environments/app/dev.env
    depends_on:
      - ca-db
    networks:
      - ca-nw
volumes:
  ca-db-vl:
networks:
  ca-nw:
    name: ca-nw
    driver: bridge