# Generated by Django 4.2.11 on 2024-04-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('a', models.DecimalField(decimal_places=2, max_digits=8)),
                ('b', models.DecimalField(decimal_places=2, max_digits=8)),
                ('t_0', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
