# Generated by Django 4.2.11 on 2024-06-03 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StiffenedPlate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phi', models.DecimalField(decimal_places=4, max_digits=5)),
                ('N_ls', models.IntegerField()),
                ('N_ts', models.IntegerField()),
                ('k', models.DecimalField(decimal_places=3, max_digits=6)),
                ('t_1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('h_s', models.DecimalField(decimal_places=2, max_digits=6)),
                ('t_s', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(null=True)),
                ('plate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csg.plate')),
            ],
        ),
    ]
