# Generated by Django 4.2.11 on 2024-06-03 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csg', '0002_stiffenedplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stiffenedplate',
            old_name='plate_id',
            new_name='plate',
        ),
    ]
