# Generated by Django 4.2.11 on 2024-06-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csg', '0003_rename_plate_id_stiffenedplate_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stiffenedplate',
            name='h_s',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='stiffenedplate',
            name='t_1',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='stiffenedplate',
            name='t_s',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
