# Generated by Django 5.1.1 on 2024-10-23 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csg', '0006_stiffenedplate_t_eq_ls_stiffenedplate_t_eq_ts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stiffenedplate',
            name='area_ls',
        ),
        migrations.RemoveField(
            model_name='stiffenedplate',
            name='area_ts',
        ),
        migrations.RemoveField(
            model_name='stiffenedplate',
            name='length_ls',
        ),
        migrations.RemoveField(
            model_name='stiffenedplate',
            name='length_ts',
        ),
        migrations.RemoveField(
            model_name='stiffenedplate',
            name='t_eq_ls',
        ),
        migrations.RemoveField(
            model_name='stiffenedplate',
            name='t_eq_ts',
        ),
    ]
