# Generated by Django 5.1.1 on 2024-10-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csg', '0008_plate_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stiffenedplate',
            name='phi',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
