# Generated by Django 4.2.13 on 2024-07-06 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('csg', '0004_alter_stiffenedplate_h_s_alter_stiffenedplate_t_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('young_modulus', models.DecimalField(decimal_places=2, max_digits=8)),
                ('poisson_ration', models.DecimalField(decimal_places=3, max_digits=4)),
                ('yielding_stress', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='StiffenedPlateAnalysis',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mesh_size', models.DecimalField(decimal_places=1, max_digits=4)),
                ('description', models.TextField(null=True)),
                ('results_dir_path', models.TextField(null=True)),
                ('rst_file_path', models.TextField(null=True)),
                ('lgw_file_path', models.TextField(null=True)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbeb.material')),
                ('stiffened_plate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csg.stiffenedplate')),
            ],
        ),
        migrations.CreateModel(
            name='BiaxialElasticBuckling',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('csi_y', models.DecimalField(decimal_places=3, max_digits=4)),
                ('n_cr', models.DecimalField(decimal_places=2, max_digits=7)),
                ('sigma_cr', models.DecimalField(decimal_places=2, max_digits=7)),
                ('w_max', models.DecimalField(decimal_places=4, max_digits=8)),
                ('stiffened_plate_analysis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbeb.stiffenedplateanalysis')),
            ],
        ),
    ]
