# Generated by Django 4.2.13 on 2024-07-06 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbeb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biaxialelasticbuckling',
            old_name='stiffened_plate_analysis_id',
            new_name='stiffened_plate_analysis',
        ),
        migrations.RenameField(
            model_name='stiffenedplateanalysis',
            old_name='material_id',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='stiffenedplateanalysis',
            old_name='stiffened_plate_id',
            new_name='stiffened_plate',
        ),
    ]
