# Generated by Django 5.0.7 on 2024-07-19 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbeb', '0002_rename_stiffened_plate_analysis_id_biaxialelasticbuckling_stiffened_plate_analysis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stiffenedplateanalysis',
            old_name='description',
            new_name='analysis_dir_path',
        ),
        migrations.RenameField(
            model_name='stiffenedplateanalysis',
            old_name='lgw_file_path',
            new_name='analysis_lgw_file_path',
        ),
        migrations.RenameField(
            model_name='stiffenedplateanalysis',
            old_name='results_dir_path',
            new_name='analysis_rst_file_path',
        ),
        migrations.RenameField(
            model_name='stiffenedplateanalysis',
            old_name='rst_file_path',
            new_name='case_study',
        ),
    ]
