# Generated by Django 5.0.7 on 2024-07-24 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbeb', '0003_rename_description_stiffenedplateanalysis_analysis_dir_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='poisson_ration',
            new_name='poisson_ratio',
        ),
    ]
