# Generated by Django 5.0.7 on 2024-07-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbeb', '0004_rename_poisson_ration_material_poisson_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='biaxialelasticbuckling',
            name='n_x',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stiffenedplateanalysis',
            name='num_elem',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
