# Generated by Django 5.0.7 on 2024-07-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbeb', '0005_biaxialelasticbuckling_n_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biaxialelasticbuckling',
            name='n_cr',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='biaxialelasticbuckling',
            name='sigma_cr',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='biaxialelasticbuckling',
            name='w_max',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
    ]
