# Generated by Django 5.0.7 on 2024-08-05 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbeb', '0006_alter_biaxialelasticbuckling_n_cr_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BiaxialElasticBuckling',
            new_name='ElasticBuckling',
        ),
    ]
