# Generated by Django 5.0.7 on 2024-08-05 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbeb', '0007_rename_biaxialelasticbuckling_elasticbuckling'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elasticbuckling',
            old_name='w_max',
            new_name='w_center',
        ),
    ]
