# Generated by Django 5.0.7 on 2024-08-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbeb', '0008_rename_w_max_elasticbuckling_w_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='tang_modulus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
