# Generated by Django 5.0.7 on 2024-08-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbeb', '0009_material_tang_modulus'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucklingType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
            ],
        ),
    ]
