# Generated by Django 5.0.7 on 2024-08-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbeb', '0010_bucklingtype_processingstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BucklingType',
            new_name='BucklingLoadType',
        ),
    ]
