# Generated by Django 5.0.7 on 2024-08-09 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbeb', '0012_stiffenedplateanalysis_buckling_load_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stiffenedplateanalysis',
            name='elastic_buckling_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elastic_buckling_stiffenedplateanalysis_set', to='cbeb.processingstatus'),
        ),
        migrations.AddField(
            model_name='stiffenedplateanalysis',
            name='elastoplastic_buckling_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elastoplastic_buckling_stiffenedplateanalysis_set', to='cbeb.processingstatus'),
        ),
    ]
