# Generated by Django 5.0.7 on 2024-08-12 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbeb', '0013_stiffenedplateanalysis_elastic_buckling_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stiffenedplateanalysis',
            old_name='elastoplastic_buckling_status',
            new_name='elasto_plastic_buckling_status',
        ),
        migrations.CreateModel(
            name='ElastoPlasticBuckling',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('n_yield', models.DecimalField(decimal_places=3, max_digits=7)),
                ('n_u', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('sigma_u', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('w_max', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('w_dist_img_path', models.TextField(null=True)),
                ('von_mises_dist_img_path', models.TextField(null=True)),
                ('stiffened_plate_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbeb.stiffenedplateanalysis')),
            ],
        ),
    ]
