# Generated by Django 5.0.7 on 2024-08-12 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbeb', '0014_rename_elastoplastic_buckling_status_stiffenedplateanalysis_elasto_plastic_buckling_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elastoplasticbuckling',
            name='n_yield',
        ),
    ]
