# Generated by Django 5.1.1 on 2024-10-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbeb', '0015_remove_elastoplasticbuckling_n_yield'),
    ]

    operations = [
        migrations.AddField(
            model_name='elastoplasticbuckling',
            name='p_u',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='elastoplasticbuckling',
            name='n_u',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='elastoplasticbuckling',
            name='sigma_u',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
