# Generated by Django 5.1.1 on 2024-10-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbeb', '0016_elastoplasticbuckling_p_u_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elasticbuckling',
            name='sigma_cr',
        ),
        migrations.AddField(
            model_name='elasticbuckling',
            name='sigma_cr_ls',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='elasticbuckling',
            name='sigma_cr_ts',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
