# Generated by Django 5.1.1 on 2024-10-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbeb', '0017_remove_elasticbuckling_sigma_cr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elastoplasticbuckling',
            old_name='p_u',
            new_name='p_u_ls',
        ),
        migrations.RenameField(
            model_name='elastoplasticbuckling',
            old_name='sigma_u',
            new_name='p_u_ts',
        ),
        migrations.RemoveField(
            model_name='elasticbuckling',
            name='csi_y',
        ),
        migrations.RemoveField(
            model_name='elasticbuckling',
            name='n_x',
        ),
        migrations.AddField(
            model_name='elastoplasticbuckling',
            name='sigma_u_ls',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='elastoplasticbuckling',
            name='sigma_u_ts',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
