# Generated by Django 5.1.1 on 2024-10-23 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbeb', '0018_rename_p_u_elastoplasticbuckling_p_u_ls_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elasticbuckling',
            old_name='sigma_cr_ls',
            new_name='sigma_cr',
        ),
        migrations.RenameField(
            model_name='elastoplasticbuckling',
            old_name='sigma_u_ls',
            new_name='sigma_u',
        ),
        migrations.RemoveField(
            model_name='elasticbuckling',
            name='sigma_cr_ts',
        ),
        migrations.RemoveField(
            model_name='elastoplasticbuckling',
            name='sigma_u_ts',
        ),
    ]
