# Generated by Django 5.1.1 on 2024-10-24 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbeb', '0019_rename_sigma_cr_ls_elasticbuckling_sigma_cr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elastoplasticbuckling',
            old_name='p_u_ls',
            new_name='p_u',
        ),
        migrations.RemoveField(
            model_name='elastoplasticbuckling',
            name='p_u_ts',
        ),
    ]
