# Generated by Django 5.1.1 on 2024-10-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbeb', '0020_rename_p_u_ls_elastoplasticbuckling_p_u_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elastoplasticbuckling',
            name='n_u',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='elastoplasticbuckling',
            name='w_max',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True),
        ),
    ]
